import "@/styles/globals.css";
import { ReactNode } from "react";
import { Header } from "@/components/header";
import Footer from "../components/footer";
import { ScrollToTopButton } from "@/components/scroll-to-top-button";
import { Providers } from "@/components/providers";

import localFont from "next/font/local";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export const metadata = {
  title: "형주의 블로그",
  description: "Generated by Next.js",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang={"ko"} suppressHydrationWarning>
      <body className={pretendard.className}>
        <Providers>
          <Header />
          <main className={"mx-auto flex max-w-[60rem] justify-center"}>
            {/*TODO: x-scroll overflow-hidden으로 임시 해결(원인 파악하기)*/}
            <div className={"overflow-hidden px-6 py-4"}>{children}</div>
          </main>
          <Footer />
          <ScrollToTopButton />
        </Providers>
      </body>
    </html>
  );
}
